[tool.ruff]
# Enable pycodestyle (`E`), Pyflakes (`F`), and import sorting (`I`)
lint.select = ["E", "F", "I"]

# Same as Black.
line-length = 88
indent-width = 4

# Assume Python 3.8
target-version = "py38"

[tool.ruff.format]
# Use single quotes for strings
quote-style = "double"

# Indent with spaces
indent-style = "space"

# Include trailing commas
skip-magic-trailing-comma = false